blank_issues_enabled: false
contact_links:
  - name: Questions and show-and-tell
    url: https://github.com/deepseek-ai/deepseek-harness/discussions
    about: Please use the DeepSeek Harness Discussions for usage questions.
